export const files = [
  {
    key: 1,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "35.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 2,
    file: { name: "イベント１.jpg", type: "img" },
    datecreate: "1 day ago",
    size: "34.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 3,
    file: { name: "イベント２.mp4", type: "video" },
    datecreate: "3 day ago",
    size: "35.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 4,
    file: { name: "申し込み.zip", type: "zip" },
    datecreate: "2 day ago",
    size: "36.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 5,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "37.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 6,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "23.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 7,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "35.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 8,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "35.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 9,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "35.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 10,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "35.5MB",
    dateupdate: "2022/01/25",
  },
  {
    key: 11,
    file: { name: "発注書.docx", type: "doc" },
    datecreate: "2day ago",
    size: "35.5MB",
    dateupdate: "2022/01/25",
  },
];
